version: '3.8'

services:
  redis:
    image: redis:alpine
    container_name: redis-broker
    ports:
      - "6379:6379"
    restart: always
    networks:
      - app_network

  publisher:
    build:
      context: ./publisher
      dockerfile: Dockerfile
    container_name: redis-publisher
    environment:
      - REDIS_URL=redis://redis:6379
    depends_on:
      - redis
    ports:
      - "3001:3001"
    networks:
      - app_network

  subscriber:
    build:
      context: ./subscriber
      dockerfile: Dockerfile
    container_name: redis-subscriber
    environment:
      - REDIS_URL=redis://redis:6379
    depends_on:
      - redis
    networks:
      - app_network

networks:
  app_network:
    driver: bridge
    driver_opts:
      com.docker.network.enable_ipv6: 'false'

